-- ✅ COMPLETE 12-Week SQL Migration - Admin Training Plan
-- Matches GeneratedSession schema exactly
-- Run this once to populate cmdhtwtil00000vg18swahirhu account with full training plan

-- 🗑️ STEP 1: Clean existing sessions (if any)
DELETE FROM generated_sessions WHERE "userId" = 'cmdhtwtil00000vg18swahirhu';

-- 🏗️ STEP 2: Insert all 12 weeks of training sessions
INSERT INTO generated_sessions (
  "id", "userId", "week", "dayOfWeek", "sessionType", "sessionSubType",
  "distance", "pace", "scheduledTime", "isRunningClub", "warmup",
  "mainSet", "cooldown", "targetRPE", "aiReason", "generatedAt"
) VALUES

-- ==================== WEEK 1 (Base Phase) ====================
('admin-w1-mon-gym', 'cmdhtwtil00000vg18swahirhu', 1, 'Monday', 'GYM', 'push', NULL, NULL, '04:30', false, NULL, 'Push Day: Chest, Shoulders, Triceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Base building with strength foundation', NOW()),
('admin-w1-mon-run', 'cmdhtwtil00000vg18swahirhu', 1, 'Monday', 'RUNNING', 'easy', 5.0, '6:32', '17:00', true, '10 min easy jog + dynamic stretching', '5km steady at easy pace with MadeRunning', '5 min walk + stretching', '{"min": 3, "max": 5, "description": "Easy aerobic pace"}', 'Base building easy aerobic run', NOW()),
('admin-w1-tue-gym', 'cmdhtwtil00000vg18swahirhu', 1, 'Tuesday', 'GYM', 'pull', NULL, NULL, '04:30', false, NULL, 'Pull Day: Back, Biceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Base building with strength foundation', NOW()),
('admin-w1-wed-run', 'cmdhtwtil00000vg18swahirhu', 1, 'Wednesday', 'RUNNING', 'tempo', 5.0, '5:13', '05:00', true, '15 min easy + 4x100m strides', '3km tempo at threshold pace with MadeRunning', '10 min easy jog + stretching', '{"min": 6, "max": 8, "description": "Comfortably hard tempo"}', 'Base building tempo work', NOW()),
('admin-w1-wed-gym', 'cmdhtwtil00000vg18swahirhu', 1, 'Wednesday', 'GYM', 'legs', NULL, NULL, '06:00', false, NULL, 'Legs Day: Quads, Hamstrings, Glutes, Calves', NULL, '{"min": 7, "max": 9, "description": "High gym intensity"}', 'Base building with strength foundation', NOW()),
('admin-w1-thu-gym', 'cmdhtwtil00000vg18swahirhu', 1, 'Thursday', 'GYM', 'push', NULL, NULL, '04:30', false, NULL, 'Push Day: Chest, Shoulders, Triceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Base building with strength foundation', NOW()),
('admin-w1-thu-run', 'cmdhtwtil00000vg18swahirhu', 1, 'Thursday', 'RUNNING', 'easy', 5.0, '6:32', '18:00', false, '10 min easy jog + dynamic stretching', '5km steady at easy pace (solo)', '5 min walk + stretching', '{"min": 3, "max": 5, "description": "Easy aerobic pace"}', 'Base building easy aerobic run', NOW()),
('admin-w1-fri-gym', 'cmdhtwtil00000vg18swahirhu', 1, 'Friday', 'GYM', 'pull', NULL, NULL, '04:30', false, NULL, 'Pull Day: Back, Biceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Base building with strength foundation', NOW()),
('admin-w1-sat-gym', 'cmdhtwtil00000vg18swahirhu', 1, 'Saturday', 'GYM', 'legs', NULL, NULL, '06:00', false, NULL, 'Legs Day: Quads, Hamstrings, Glutes, Calves', NULL, '{"min": 7, "max": 9, "description": "High gym intensity"}', 'Base building with strength foundation', NOW()),
('admin-w1-sat-run', 'cmdhtwtil00000vg18swahirhu', 1, 'Saturday', 'RUNNING', 'long', 8.0, '6:32', '09:00', true, '15 min easy jog + dynamic stretching', '8km progressive long run with MadeRunning', '10 min walk + full stretching routine', '{"min": 5, "max": 7, "description": "Steady long run effort"}', 'Base building long run', NOW()),
('admin-w1-sun-rest', 'cmdhtwtil00000vg18swahirhu', 1, 'Sunday', 'REST', 'easy', NULL, NULL, NULL, false, NULL, 'Rest Day - Recovery & Stretching', NULL, '{"min": 1, "max": 2, "description": "Complete rest"}', 'Recovery day for adaptation', NOW()),

-- ==================== WEEK 2 (Base Phase) ====================
('admin-w2-mon-gym', 'cmdhtwtil00000vg18swahirhu', 2, 'Monday', 'GYM', 'push', NULL, NULL, '04:30', false, NULL, 'Push Day: Chest, Shoulders, Triceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Base building with strength foundation', NOW()),
('admin-w2-mon-run', 'cmdhtwtil00000vg18swahirhu', 2, 'Monday', 'RUNNING', 'easy', 6.0, '6:32', '17:00', true, '10 min easy jog + dynamic stretching', '6km steady at easy pace with MadeRunning', '5 min walk + stretching', '{"min": 3, "max": 5, "description": "Easy aerobic pace"}', 'Base building easy aerobic run', NOW()),
('admin-w2-tue-gym', 'cmdhtwtil00000vg18swahirhu', 2, 'Tuesday', 'GYM', 'pull', NULL, NULL, '04:30', false, NULL, 'Pull Day: Back, Biceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Base building with strength foundation', NOW()),
('admin-w2-wed-run', 'cmdhtwtil00000vg18swahirhu', 2, 'Wednesday', 'RUNNING', 'tempo', 6.0, '5:13', '05:00', true, '15 min easy + 4x100m strides', '4km tempo at threshold pace with MadeRunning', '10 min easy jog + stretching', '{"min": 6, "max": 8, "description": "Comfortably hard tempo"}', 'Base building tempo work', NOW()),
('admin-w2-wed-gym', 'cmdhtwtil00000vg18swahirhu', 2, 'Wednesday', 'GYM', 'legs', NULL, NULL, '06:00', false, NULL, 'Legs Day: Quads, Hamstrings, Glutes, Calves', NULL, '{"min": 7, "max": 9, "description": "High gym intensity"}', 'Base building with strength foundation', NOW()),
('admin-w2-thu-gym', 'cmdhtwtil00000vg18swahirhu', 2, 'Thursday', 'GYM', 'push', NULL, NULL, '04:30', false, NULL, 'Push Day: Chest, Shoulders, Triceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Base building with strength foundation', NOW()),
('admin-w2-thu-run', 'cmdhtwtil00000vg18swahirhu', 2, 'Thursday', 'RUNNING', 'easy', 6.0, '6:32', '18:00', false, '10 min easy jog + dynamic stretching', '6km steady at easy pace (solo)', '5 min walk + stretching', '{"min": 3, "max": 5, "description": "Easy aerobic pace"}', 'Base building easy aerobic run', NOW()),
('admin-w2-fri-gym', 'cmdhtwtil00000vg18swahirhu', 2, 'Friday', 'GYM', 'pull', NULL, NULL, '04:30', false, NULL, 'Pull Day: Back, Biceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Base building with strength foundation', NOW()),
('admin-w2-sat-gym', 'cmdhtwtil00000vg18swahirhu', 2, 'Saturday', 'GYM', 'legs', NULL, NULL, '06:00', false, NULL, 'Legs Day: Quads, Hamstrings, Glutes, Calves', NULL, '{"min": 7, "max": 9, "description": "High gym intensity"}', 'Base building with strength foundation', NOW()),
('admin-w2-sat-run', 'cmdhtwtil00000vg18swahirhu', 2, 'Saturday', 'RUNNING', 'long', 10.0, '6:32', '09:00', true, '15 min easy jog + dynamic stretching', '10km progressive long run with MadeRunning', '10 min walk + full stretching routine', '{"min": 5, "max": 7, "description": "Steady long run effort"}', 'Base building long run', NOW()),
('admin-w2-sun-rest', 'cmdhtwtil00000vg18swahirhu', 2, 'Sunday', 'REST', 'easy', NULL, NULL, NULL, false, NULL, 'Rest Day - Recovery & Stretching', NULL, '{"min": 1, "max": 2, "description": "Complete rest"}', 'Recovery day for adaptation', NOW()),

-- ==================== WEEK 3 (Base Phase) ====================
('admin-w3-mon-gym', 'cmdhtwtil00000vg18swahirhu', 3, 'Monday', 'GYM', 'push', NULL, NULL, '04:30', false, NULL, 'Push Day: Chest, Shoulders, Triceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Base building with strength foundation', NOW()),
('admin-w3-mon-run', 'cmdhtwtil00000vg18swahirhu', 3, 'Monday', 'RUNNING', 'easy', 7.0, '6:32', '17:00', true, '10 min easy jog + dynamic stretching', '7km steady at easy pace with MadeRunning', '5 min walk + stretching', '{"min": 3, "max": 5, "description": "Easy aerobic pace"}', 'Base building easy aerobic run', NOW()),
('admin-w3-tue-gym', 'cmdhtwtil00000vg18swahirhu', 3, 'Tuesday', 'GYM', 'pull', NULL, NULL, '04:30', false, NULL, 'Pull Day: Back, Biceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Base building with strength foundation', NOW()),
('admin-w3-wed-run', 'cmdhtwtil00000vg18swahirhu', 3, 'Wednesday', 'RUNNING', 'tempo', 7.0, '5:13', '05:00', true, '15 min easy + 4x100m strides', '5km tempo at threshold pace with MadeRunning', '10 min easy jog + stretching', '{"min": 6, "max": 8, "description": "Comfortably hard tempo"}', 'Base building tempo work', NOW()),
('admin-w3-wed-gym', 'cmdhtwtil00000vg18swahirhu', 3, 'Wednesday', 'GYM', 'legs', NULL, NULL, '06:00', false, NULL, 'Legs Day: Quads, Hamstrings, Glutes, Calves', NULL, '{"min": 7, "max": 9, "description": "High gym intensity"}', 'Base building with strength foundation', NOW()),
('admin-w3-thu-gym', 'cmdhtwtil00000vg18swahirhu', 3, 'Thursday', 'GYM', 'push', NULL, NULL, '04:30', false, NULL, 'Push Day: Chest, Shoulders, Triceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Base building with strength foundation', NOW()),
('admin-w3-thu-run', 'cmdhtwtil00000vg18swahirhu', 3, 'Thursday', 'RUNNING', 'easy', 7.0, '6:32', '18:00', false, '10 min easy jog + dynamic stretching', '7km steady at easy pace (solo)', '5 min walk + stretching', '{"min": 3, "max": 5, "description": "Easy aerobic pace"}', 'Base building easy aerobic run', NOW()),
('admin-w3-fri-gym', 'cmdhtwtil00000vg18swahirhu', 3, 'Friday', 'GYM', 'pull', NULL, NULL, '04:30', false, NULL, 'Pull Day: Back, Biceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Base building with strength foundation', NOW()),
('admin-w3-sat-gym', 'cmdhtwtil00000vg18swahirhu', 3, 'Saturday', 'GYM', 'legs', NULL, NULL, '06:00', false, NULL, 'Legs Day: Quads, Hamstrings, Glutes, Calves', NULL, '{"min": 7, "max": 9, "description": "High gym intensity"}', 'Base building with strength foundation', NOW()),
('admin-w3-sat-run', 'cmdhtwtil00000vg18swahirhu', 3, 'Saturday', 'RUNNING', 'long', 12.0, '6:32', '09:00', true, '15 min easy jog + dynamic stretching', '12km progressive long run with MadeRunning', '10 min walk + full stretching routine', '{"min": 5, "max": 7, "description": "Steady long run effort"}', 'Base building long run', NOW()),
('admin-w3-sun-rest', 'cmdhtwtil00000vg18swahirhu', 3, 'Sunday', 'REST', 'easy', NULL, NULL, NULL, false, NULL, 'Rest Day - Recovery & Stretching', NULL, '{"min": 1, "max": 2, "description": "Complete rest"}', 'Recovery day for adaptation', NOW()),

-- ==================== WEEK 4 (Base Phase - Recovery) ====================
('admin-w4-mon-gym', 'cmdhtwtil00000vg18swahirhu', 4, 'Monday', 'GYM', 'push', NULL, NULL, '04:30', false, NULL, 'Push Day: Chest, Shoulders, Triceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Base recovery week', NOW()),
('admin-w4-mon-run', 'cmdhtwtil00000vg18swahirhu', 4, 'Monday', 'RUNNING', 'easy', 5.0, '6:32', '17:00', true, '10 min easy jog + dynamic stretching', '5km steady at easy pace with MadeRunning', '5 min walk + stretching', '{"min": 3, "max": 5, "description": "Easy aerobic pace"}', 'Base recovery week easy run', NOW()),
('admin-w4-tue-gym', 'cmdhtwtil00000vg18swahirhu', 4, 'Tuesday', 'GYM', 'pull', NULL, NULL, '04:30', false, NULL, 'Pull Day: Back, Biceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Base recovery week', NOW()),
('admin-w4-wed-run', 'cmdhtwtil00000vg18swahirhu', 4, 'Wednesday', 'RUNNING', 'tempo', 5.0, '5:13', '05:00', true, '15 min easy + 4x100m strides', '3km tempo at threshold pace with MadeRunning', '10 min easy jog + stretching', '{"min": 6, "max": 8, "description": "Comfortably hard tempo"}', 'Base recovery week tempo', NOW()),
('admin-w4-wed-gym', 'cmdhtwtil00000vg18swahirhu', 4, 'Wednesday', 'GYM', 'legs', NULL, NULL, '06:00', false, NULL, 'Legs Day: Quads, Hamstrings, Glutes, Calves', NULL, '{"min": 7, "max": 9, "description": "High gym intensity"}', 'Base recovery week', NOW()),
('admin-w4-thu-gym', 'cmdhtwtil00000vg18swahirhu', 4, 'Thursday', 'GYM', 'push', NULL, NULL, '04:30', false, NULL, 'Push Day: Chest, Shoulders, Triceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Base recovery week', NOW()),
('admin-w4-thu-run', 'cmdhtwtil00000vg18swahirhu', 4, 'Thursday', 'RUNNING', 'easy', 5.0, '6:32', '18:00', false, '10 min easy jog + dynamic stretching', '5km steady at easy pace (solo)', '5 min walk + stretching', '{"min": 3, "max": 5, "description": "Easy aerobic pace"}', 'Base recovery week easy run', NOW()),
('admin-w4-fri-gym', 'cmdhtwtil00000vg18swahirhu', 4, 'Friday', 'GYM', 'pull', NULL, NULL, '04:30', false, NULL, 'Pull Day: Back, Biceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Base recovery week', NOW()),
('admin-w4-sat-gym', 'cmdhtwtil00000vg18swahirhu', 4, 'Saturday', 'GYM', 'legs', NULL, NULL, '06:00', false, NULL, 'Legs Day: Quads, Hamstrings, Glutes, Calves', NULL, '{"min": 7, "max": 9, "description": "High gym intensity"}', 'Base recovery week', NOW()),
('admin-w4-sat-run', 'cmdhtwtil00000vg18swahirhu', 4, 'Saturday', 'RUNNING', 'long', 10.0, '6:32', '09:00', true, '15 min easy jog + dynamic stretching', '10km progressive long run with MadeRunning', '10 min walk + full stretching routine', '{"min": 5, "max": 7, "description": "Steady long run effort"}', 'Base recovery week long run', NOW()),
('admin-w4-sun-rest', 'cmdhtwtil00000vg18swahirhu', 4, 'Sunday', 'REST', 'easy', NULL, NULL, NULL, false, NULL, 'Rest Day - Recovery & Stretching', NULL, '{"min": 1, "max": 2, "description": "Complete rest"}', 'Recovery day for adaptation', NOW()),

-- ==================== WEEK 5 (Build Phase) ====================
('admin-w5-mon-gym', 'cmdhtwtil00000vg18swahirhu', 5, 'Monday', 'GYM', 'push', NULL, NULL, '04:30', false, NULL, 'Push Day: Chest, Shoulders, Triceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Build phase strength development', NOW()),
('admin-w5-mon-run', 'cmdhtwtil00000vg18swahirhu', 5, 'Monday', 'RUNNING', 'easy', 6.0, '6:32', '17:00', true, '10 min easy jog + dynamic stretching', '6km steady at easy pace with MadeRunning', '5 min walk + stretching', '{"min": 3, "max": 5, "description": "Easy aerobic pace"}', 'Build phase aerobic development', NOW()),
('admin-w5-tue-gym', 'cmdhtwtil00000vg18swahirhu', 5, 'Tuesday', 'GYM', 'pull', NULL, NULL, '04:30', false, NULL, 'Pull Day: Back, Biceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Build phase strength development', NOW()),
('admin-w5-wed-run', 'cmdhtwtil00000vg18swahirhu', 5, 'Wednesday', 'RUNNING', 'tempo', 7.0, '5:13', '05:00', true, '15 min easy + 4x100m strides', '5km tempo at threshold pace with MadeRunning', '10 min easy jog + stretching', '{"min": 6, "max": 8, "description": "Comfortably hard tempo"}', 'Build phase tempo development', NOW()),
('admin-w5-wed-gym', 'cmdhtwtil00000vg18swahirhu', 5, 'Wednesday', 'GYM', 'legs', NULL, NULL, '06:00', false, NULL, 'Legs Day: Quads, Hamstrings, Glutes, Calves', NULL, '{"min": 7, "max": 9, "description": "High gym intensity"}', 'Build phase strength development', NOW()),
('admin-w5-thu-gym', 'cmdhtwtil00000vg18swahirhu', 5, 'Thursday', 'GYM', 'push', NULL, NULL, '04:30', false, NULL, 'Push Day: Chest, Shoulders, Triceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Build phase strength development', NOW()),
('admin-w5-thu-run', 'cmdhtwtil00000vg18swahirhu', 5, 'Thursday', 'RUNNING', 'easy', 6.0, '6:32', '18:00', false, '10 min easy jog + dynamic stretching', '6km steady at easy pace (solo)', '5 min walk + stretching', '{"min": 3, "max": 5, "description": "Easy aerobic pace"}', 'Build phase aerobic development', NOW()),
('admin-w5-fri-gym', 'cmdhtwtil00000vg18swahirhu', 5, 'Friday', 'GYM', 'pull', NULL, NULL, '04:30', false, NULL, 'Pull Day: Back, Biceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Build phase strength development', NOW()),
('admin-w5-sat-gym', 'cmdhtwtil00000vg18swahirhu', 5, 'Saturday', 'GYM', 'legs', NULL, NULL, '06:00', false, NULL, 'Legs Day: Quads, Hamstrings, Glutes, Calves', NULL, '{"min": 7, "max": 9, "description": "High gym intensity"}', 'Build phase strength development', NOW()),
('admin-w5-sat-run', 'cmdhtwtil00000vg18swahirhu', 5, 'Saturday', 'RUNNING', 'long', 14.0, '6:32', '09:00', true, '15 min easy jog + dynamic stretching', '14km progressive long run with MadeRunning', '10 min walk + full stretching routine', '{"min": 5, "max": 7, "description": "Steady long run effort"}', 'Build phase long run', NOW()),
('admin-w5-sun-rest', 'cmdhtwtil00000vg18swahirhu', 5, 'Sunday', 'REST', 'easy', NULL, NULL, NULL, false, NULL, 'Rest Day - Recovery & Stretching', NULL, '{"min": 1, "max": 2, "description": "Complete rest"}', 'Recovery day for adaptation', NOW()),

-- ==================== WEEK 6 (Build Phase) ====================
('admin-w6-mon-gym', 'cmdhtwtil00000vg18swahirhu', 6, 'Monday', 'GYM', 'push', NULL, NULL, '04:30', false, NULL, 'Push Day: Chest, Shoulders, Triceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Build phase strength development', NOW()),
('admin-w6-mon-run', 'cmdhtwtil00000vg18swahirhu', 6, 'Monday', 'RUNNING', 'easy', 7.0, '6:32', '17:00', true, '10 min easy jog + dynamic stretching', '7km steady at easy pace with MadeRunning', '5 min walk + stretching', '{"min": 3, "max": 5, "description": "Easy aerobic pace"}', 'Build phase aerobic development', NOW()),
('admin-w6-tue-gym', 'cmdhtwtil00000vg18swahirhu', 6, 'Tuesday', 'GYM', 'pull', NULL, NULL, '04:30', false, NULL, 'Pull Day: Back, Biceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Build phase strength development', NOW()),
('admin-w6-wed-run', 'cmdhtwtil00000vg18swahirhu', 6, 'Wednesday', 'RUNNING', 'tempo', 8.0, '5:13', '05:00', true, '15 min easy + 4x100m strides', '6km tempo at threshold pace with MadeRunning', '10 min easy jog + stretching', '{"min": 6, "max": 8, "description": "Comfortably hard tempo"}', 'Build phase tempo development', NOW()),
('admin-w6-wed-gym', 'cmdhtwtil00000vg18swahirhu', 6, 'Wednesday', 'GYM', 'legs', NULL, NULL, '06:00', false, NULL, 'Legs Day: Quads, Hamstrings, Glutes, Calves', NULL, '{"min": 7, "max": 9, "description": "High gym intensity"}', 'Build phase strength development', NOW()),
('admin-w6-thu-gym', 'cmdhtwtil00000vg18swahirhu', 6, 'Thursday', 'GYM', 'push', NULL, NULL, '04:30', false, NULL, 'Push Day: Chest, Shoulders, Triceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Build phase strength development', NOW()),
('admin-w6-thu-run', 'cmdhtwtil00000vg18swahirhu', 6, 'Thursday', 'RUNNING', 'easy', 7.0, '6:32', '18:00', false, '10 min easy jog + dynamic stretching', '7km steady at easy pace (solo)', '5 min walk + stretching', '{"min": 3, "max": 5, "description": "Easy aerobic pace"}', 'Build phase aerobic development', NOW()),
('admin-w6-fri-gym', 'cmdhtwtil00000vg18swahirhu', 6, 'Friday', 'GYM', 'pull', NULL, NULL, '04:30', false, NULL, 'Pull Day: Back, Biceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Build phase strength development', NOW()),
('admin-w6-sat-gym', 'cmdhtwtil00000vg18swahirhu', 6, 'Saturday', 'GYM', 'legs', NULL, NULL, '06:00', false, NULL, 'Legs Day: Quads, Hamstrings, Glutes, Calves', NULL, '{"min": 7, "max": 9, "description": "High gym intensity"}', 'Build phase strength development', NOW()),
('admin-w6-sat-run', 'cmdhtwtil00000vg18swahirhu', 6, 'Saturday', 'RUNNING', 'long', 16.0, '6:32', '09:00', true, '15 min easy jog + dynamic stretching', '16km progressive long run with MadeRunning', '10 min walk + full stretching routine', '{"min": 5, "max": 7, "description": "Steady long run effort"}', 'Build phase long run', NOW()),
('admin-w6-sun-rest', 'cmdhtwtil00000vg18swahirhu', 6, 'Sunday', 'REST', 'easy', NULL, NULL, NULL, false, NULL, 'Rest Day - Recovery & Stretching', NULL, '{"min": 1, "max": 2, "description": "Complete rest"}', 'Recovery day for adaptation', NOW()),

-- ==================== WEEK 7 (Build Phase) ====================
('admin-w7-mon-gym', 'cmdhtwtil00000vg18swahirhu', 7, 'Monday', 'GYM', 'push', NULL, NULL, '04:30', false, NULL, 'Push Day: Chest, Shoulders, Triceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Build phase strength development', NOW()),
('admin-w7-mon-run', 'cmdhtwtil00000vg18swahirhu', 7, 'Monday', 'RUNNING', 'easy', 8.0, '6:32', '17:00', true, '10 min easy jog + dynamic stretching', '8km steady at easy pace with MadeRunning', '5 min walk + stretching', '{"min": 3, "max": 5, "description": "Easy aerobic pace"}', 'Build phase aerobic development', NOW()),
('admin-w7-tue-gym', 'cmdhtwtil00000vg18swahirhu', 7, 'Tuesday', 'GYM', 'pull', NULL, NULL, '04:30', false, NULL, 'Pull Day: Back, Biceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Build phase strength development', NOW()),
('admin-w7-wed-run', 'cmdhtwtil00000vg18swahirhu', 7, 'Wednesday', 'RUNNING', 'tempo', 9.0, '5:13', '05:00', true, '15 min easy + 4x100m strides', '7km tempo at threshold pace with MadeRunning', '10 min easy jog + stretching', '{"min": 6, "max": 8, "description": "Comfortably hard tempo"}', 'Build phase tempo development', NOW()),
('admin-w7-wed-gym', 'cmdhtwtil00000vg18swahirhu', 7, 'Wednesday', 'GYM', 'legs', NULL, NULL, '06:00', false, NULL, 'Legs Day: Quads, Hamstrings, Glutes, Calves', NULL, '{"min": 7, "max": 9, "description": "High gym intensity"}', 'Build phase strength development', NOW()),
('admin-w7-thu-gym', 'cmdhtwtil00000vg18swahirhu', 7, 'Thursday', 'GYM', 'push', NULL, NULL, '04:30', false, NULL, 'Push Day: Chest, Shoulders, Triceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Build phase strength development', NOW()),
('admin-w7-thu-run', 'cmdhtwtil00000vg18swahirhu', 7, 'Thursday', 'RUNNING', 'easy', 8.0, '6:32', '18:00', false, '10 min easy jog + dynamic stretching', '8km steady at easy pace (solo)', '5 min walk + stretching', '{"min": 3, "max": 5, "description": "Easy aerobic pace"}', 'Build phase aerobic development', NOW()),
('admin-w7-fri-gym', 'cmdhtwtil00000vg18swahirhu', 7, 'Friday', 'GYM', 'pull', NULL, NULL, '04:30', false, NULL, 'Pull Day: Back, Biceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Build phase strength development', NOW()),
('admin-w7-sat-gym', 'cmdhtwtil00000vg18swahirhu', 7, 'Saturday', 'GYM', 'legs', NULL, NULL, '06:00', false, NULL, 'Legs Day: Quads, Hamstrings, Glutes, Calves', NULL, '{"min": 7, "max": 9, "description": "High gym intensity"}', 'Build phase strength development', NOW()),
('admin-w7-sat-run', 'cmdhtwtil00000vg18swahirhu', 7, 'Saturday', 'RUNNING', 'long', 18.0, '6:32', '09:00', true, '15 min easy jog + dynamic stretching', '18km progressive long run with MadeRunning', '10 min walk + full stretching routine', '{"min": 5, "max": 7, "description": "Steady long run effort"}', 'Build phase long run', NOW()),
('admin-w7-sun-rest', 'cmdhtwtil00000vg18swahirhu', 7, 'Sunday', 'REST', 'easy', NULL, NULL, NULL, false, NULL, 'Rest Day - Recovery & Stretching', NULL, '{"min": 1, "max": 2, "description": "Complete rest"}', 'Recovery day for adaptation', NOW()),

-- ==================== WEEK 8 (Build Phase - Recovery) ====================
('admin-w8-mon-gym', 'cmdhtwtil00000vg18swahirhu', 8, 'Monday', 'GYM', 'push', NULL, NULL, '04:30', false, NULL, 'Push Day: Chest, Shoulders, Triceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Build recovery week', NOW()),
('admin-w8-mon-run', 'cmdhtwtil00000vg18swahirhu', 8, 'Monday', 'RUNNING', 'easy', 6.0, '6:32', '17:00', true, '10 min easy jog + dynamic stretching', '6km steady at easy pace with MadeRunning', '5 min walk + stretching', '{"min": 3, "max": 5, "description": "Easy aerobic pace"}', 'Build recovery week', NOW()),
('admin-w8-tue-gym', 'cmdhtwtil00000vg18swahirhu', 8, 'Tuesday', 'GYM', 'pull', NULL, NULL, '04:30', false, NULL, 'Pull Day: Back, Biceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Build recovery week', NOW()),
('admin-w8-wed-run', 'cmdhtwtil00000vg18swahirhu', 8, 'Wednesday', 'RUNNING', 'tempo', 7.0, '5:13', '05:00', true, '15 min easy + 4x100m strides', '5km tempo at threshold pace with MadeRunning', '10 min easy jog + stretching', '{"min": 6, "max": 8, "description": "Comfortably hard tempo"}', 'Build recovery week', NOW()),
('admin-w8-wed-gym', 'cmdhtwtil00000vg18swahirhu', 8, 'Wednesday', 'GYM', 'legs', NULL, NULL, '06:00', false, NULL, 'Legs Day: Quads, Hamstrings, Glutes, Calves', NULL, '{"min": 7, "max": 9, "description": "High gym intensity"}', 'Build recovery week', NOW()),
('admin-w8-thu-gym', 'cmdhtwtil00000vg18swahirhu', 8, 'Thursday', 'GYM', 'push', NULL, NULL, '04:30', false, NULL, 'Push Day: Chest, Shoulders, Triceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Build recovery week', NOW()),
('admin-w8-thu-run', 'cmdhtwtil00000vg18swahirhu', 8, 'Thursday', 'RUNNING', 'easy', 6.0, '6:32', '18:00', false, '10 min easy jog + dynamic stretching', '6km steady at easy pace (solo)', '5 min walk + stretching', '{"min": 3, "max": 5, "description": "Easy aerobic pace"}', 'Build recovery week', NOW()),
('admin-w8-fri-gym', 'cmdhtwtil00000vg18swahirhu', 8, 'Friday', 'GYM', 'pull', NULL, NULL, '04:30', false, NULL, 'Pull Day: Back, Biceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Build recovery week', NOW()),
('admin-w8-sat-gym', 'cmdhtwtil00000vg18swahirhu', 8, 'Saturday', 'GYM', 'legs', NULL, NULL, '06:00', false, NULL, 'Legs Day: Quads, Hamstrings, Glutes, Calves', NULL, '{"min": 7, "max": 9, "description": "High gym intensity"}', 'Build recovery week', NOW()),
('admin-w8-sat-run', 'cmdhtwtil00000vg18swahirhu', 8, 'Saturday', 'RUNNING', 'long', 16.0, '6:32', '09:00', true, '15 min easy jog + dynamic stretching', '16km progressive long run with MadeRunning', '10 min walk + full stretching routine', '{"min": 5, "max": 7, "description": "Steady long run effort"}', 'Build recovery week', NOW()),
('admin-w8-sun-rest', 'cmdhtwtil00000vg18swahirhu', 8, 'Sunday', 'REST', 'easy', NULL, NULL, NULL, false, NULL, 'Rest Day - Recovery & Stretching', NULL, '{"min": 1, "max": 2, "description": "Complete rest"}', 'Recovery day for adaptation', NOW()),

-- ==================== WEEK 9 (Peak Phase) ====================
('admin-w9-mon-gym', 'cmdhtwtil00000vg18swahirhu', 9, 'Monday', 'GYM', 'push', NULL, NULL, '04:30', false, NULL, 'Push Day: Chest, Shoulders, Triceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Peak phase high intensity', NOW()),
('admin-w9-mon-run', 'cmdhtwtil00000vg18swahirhu', 9, 'Monday', 'RUNNING', 'easy', 8.0, '6:32', '17:00', true, '10 min easy jog + dynamic stretching', '8km steady at easy pace with MadeRunning', '5 min walk + stretching', '{"min": 3, "max": 5, "description": "Easy aerobic pace"}', 'Peak phase aerobic support', NOW()),
('admin-w9-tue-gym', 'cmdhtwtil00000vg18swahirhu', 9, 'Tuesday', 'GYM', 'pull', NULL, NULL, '04:30', false, NULL, 'Pull Day: Back, Biceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Peak phase high intensity', NOW()),
('admin-w9-wed-run', 'cmdhtwtil00000vg18swahirhu', 9, 'Wednesday', 'RUNNING', 'tempo', 10.0, '5:13', '05:00', true, '15 min easy + 4x100m strides', '8km tempo at threshold pace with MadeRunning', '10 min easy jog + stretching', '{"min": 7, "max": 9, "description": "Hard tempo effort"}', 'Peak phase tempo work', NOW()),
('admin-w9-wed-gym', 'cmdhtwtil00000vg18swahirhu', 9, 'Wednesday', 'GYM', 'legs', NULL, NULL, '06:00', false, NULL, 'Legs Day: Quads, Hamstrings, Glutes, Calves', NULL, '{"min": 7, "max": 9, "description": "High gym intensity"}', 'Peak phase high intensity', NOW()),
('admin-w9-thu-gym', 'cmdhtwtil00000vg18swahirhu', 9, 'Thursday', 'GYM', 'push', NULL, NULL, '04:30', false, NULL, 'Push Day: Chest, Shoulders, Triceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Peak phase high intensity', NOW()),
('admin-w9-thu-run', 'cmdhtwtil00000vg18swahirhu', 9, 'Thursday', 'RUNNING', 'easy', 8.0, '6:32', '18:00', false, '10 min easy jog + dynamic stretching', '8km steady at easy pace (solo)', '5 min walk + stretching', '{"min": 3, "max": 5, "description": "Easy aerobic pace"}', 'Peak phase aerobic support', NOW()),
('admin-w9-fri-gym', 'cmdhtwtil00000vg18swahirhu', 9, 'Friday', 'GYM', 'pull', NULL, NULL, '04:30', false, NULL, 'Pull Day: Back, Biceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Peak phase high intensity', NOW()),
('admin-w9-sat-gym', 'cmdhtwtil00000vg18swahirhu', 9, 'Saturday', 'GYM', 'legs', NULL, NULL, '06:00', false, NULL, 'Legs Day: Quads, Hamstrings, Glutes, Calves', NULL, '{"min": 7, "max": 9, "description": "High gym intensity"}', 'Peak phase high intensity', NOW()),
('admin-w9-sat-run', 'cmdhtwtil00000vg18swahirhu', 9, 'Saturday', 'RUNNING', 'long', 20.0, '6:32', '09:00', true, '15 min easy jog + dynamic stretching', '20km progressive long run with MadeRunning - PEAK DISTANCE!', '10 min walk + full stretching routine', '{"min": 6, "max": 8, "description": "Strong long run effort"}', 'Peak phase long run - maximum distance', NOW()),
('admin-w9-sun-rest', 'cmdhtwtil00000vg18swahirhu', 9, 'Sunday', 'REST', 'easy', NULL, NULL, NULL, false, NULL, 'Rest Day - Recovery & Stretching', NULL, '{"min": 1, "max": 2, "description": "Complete rest"}', 'Recovery day for adaptation', NOW()),

-- ==================== WEEK 10 (Peak Phase - Recovery) ====================
('admin-w10-mon-gym', 'cmdhtwtil00000vg18swahirhu', 10, 'Monday', 'GYM', 'push', NULL, NULL, '04:30', false, NULL, 'Push Day: Chest, Shoulders, Triceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Peak recovery week', NOW()),
('admin-w10-mon-run', 'cmdhtwtil00000vg18swahirhu', 10, 'Monday', 'RUNNING', 'easy', 6.0, '6:32', '17:00', true, '10 min easy jog + dynamic stretching', '6km steady at easy pace with MadeRunning', '5 min walk + stretching', '{"min": 3, "max": 5, "description": "Easy aerobic pace"}', 'Peak recovery week', NOW()),
('admin-w10-tue-gym', 'cmdhtwtil00000vg18swahirhu', 10, 'Tuesday', 'GYM', 'pull', NULL, NULL, '04:30', false, NULL, 'Pull Day: Back, Biceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Peak recovery week', NOW()),
('admin-w10-wed-run', 'cmdhtwtil00000vg18swahirhu', 10, 'Wednesday', 'RUNNING', 'tempo', 8.0, '5:13', '05:00', true, '15 min easy + 4x100m strides', '6km tempo at threshold pace with MadeRunning', '10 min easy jog + stretching', '{"min": 6, "max": 8, "description": "Comfortably hard tempo"}', 'Peak recovery week', NOW()),
('admin-w10-wed-gym', 'cmdhtwtil00000vg18swahirhu', 10, 'Wednesday', 'GYM', 'legs', NULL, NULL, '06:00', false, NULL, 'Legs Day: Quads, Hamstrings, Glutes, Calves', NULL, '{"min": 7, "max": 9, "description": "High gym intensity"}', 'Peak recovery week', NOW()),
('admin-w10-thu-gym', 'cmdhtwtil00000vg18swahirhu', 10, 'Thursday', 'GYM', 'push', NULL, NULL, '04:30', false, NULL, 'Push Day: Chest, Shoulders, Triceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Peak recovery week', NOW()),
('admin-w10-thu-run', 'cmdhtwtil00000vg18swahirhu', 10, 'Thursday', 'RUNNING', 'easy', 6.0, '6:32', '18:00', false, '10 min easy jog + dynamic stretching', '6km steady at easy pace (solo)', '5 min walk + stretching', '{"min": 3, "max": 5, "description": "Easy aerobic pace"}', 'Peak recovery week', NOW()),
('admin-w10-fri-gym', 'cmdhtwtil00000vg18swahirhu', 10, 'Friday', 'GYM', 'pull', NULL, NULL, '04:30', false, NULL, 'Pull Day: Back, Biceps', NULL, '{"min": 6, "max": 8, "description": "Moderate gym intensity"}', 'Peak recovery week', NOW()),
('admin-w10-sat-gym', 'cmdhtwtil00000vg18swahirhu', 10, 'Saturday', 'GYM', 'legs', NULL, NULL, '06:00', false, NULL, 'Legs Day: Quads, Hamstrings, Glutes, Calves', NULL, '{"min": 7, "max": 9, "description": "High gym intensity"}', 'Peak recovery week', NOW()),
('admin-w10-sat-run', 'cmdhtwtil00000vg18swahirhu', 10, 'Saturday', 'RUNNING', 'long', 18.0, '6:32', '09:00', true, '15 min easy jog + dynamic stretching', '18km progressive long run with MadeRunning', '10 min walk + full stretching routine', '{"min": 5, "max": 7, "description": "Steady long run effort"}', 'Peak recovery week', NOW()),
('admin-w10-sun-rest', 'cmdhtwtil00000vg18swahirhu', 10, 'Sunday', 'REST', 'easy', NULL, NULL, NULL, false, NULL, 'Rest Day - Recovery & Stretching', NULL, '{"min": 1, "max": 2, "description": "Complete rest"}', 'Recovery day for adaptation', NOW()),

-- ==================== WEEK 11 (Taper Phase) ====================
('admin-w11-mon-gym', 'cmdhtwtil00000vg18swahirhu', 11, 'Monday', 'GYM', 'push', NULL, NULL, '04:30', false, NULL, 'Push Day: Chest, Shoulders, Triceps - Reduced Volume', NULL, '{"min": 5, "max": 7, "description": "Light to moderate intensity"}', 'Taper phase volume reduction', NOW()),
('admin-w11-mon-run', 'cmdhtwtil00000vg18swahirhu', 11, 'Monday', 'RUNNING', 'easy', 5.0, '6:32', '17:00', true, '10 min easy jog + dynamic stretching', '5km steady at easy pace with MadeRunning', '5 min walk + stretching', '{"min": 2, "max": 4, "description": "Very easy recovery pace"}', 'Taper phase recovery', NOW()),
('admin-w11-tue-gym', 'cmdhtwtil00000vg18swahirhu', 11, 'Tuesday', 'GYM', 'pull', NULL, NULL, '04:30', false, NULL, 'Pull Day: Back, Biceps - Reduced Volume', NULL, '{"min": 5, "max": 7, "description": "Light to moderate intensity"}', 'Taper phase volume reduction', NOW()),
('admin-w11-wed-run', 'cmdhtwtil00000vg18swahirhu', 11, 'Wednesday', 'RUNNING', 'tempo', 6.0, '5:13', '05:00', true, '15 min easy + 4x100m strides', '4km tempo at threshold pace with MadeRunning', '10 min easy jog + stretching', '{"min": 5, "max": 7, "description": "Moderate tempo effort"}', 'Taper phase sharpening', NOW()),
('admin-w11-wed-gym', 'cmdhtwtil00000vg18swahirhu', 11, 'Wednesday', 'GYM', 'legs', NULL, NULL, '06:00', false, NULL, 'Legs Day: Quads, Hamstrings, Glutes, Calves - Reduced Volume', NULL, '{"min": 5, "max": 7, "description": "Light to moderate intensity"}', 'Taper phase volume reduction', NOW()),
('admin-w11-thu-gym', 'cmdhtwtil00000vg18swahirhu', 11, 'Thursday', 'GYM', 'push', NULL, NULL, '04:30', false, NULL, 'Push Day: Chest, Shoulders, Triceps - Reduced Volume', NULL, '{"min": 5, "max": 7, "description": "Light to moderate intensity"}', 'Taper phase volume reduction', NOW()),
('admin-w11-thu-run', 'cmdhtwtil00000vg18swahirhu', 11, 'Thursday', 'RUNNING', 'easy', 5.0, '6:32', '18:00', false, '10 min easy jog + dynamic stretching', '5km steady at easy pace (solo)', '5 min walk + stretching', '{"min": 2, "max": 4, "description": "Very easy recovery pace"}', 'Taper phase recovery', NOW()),
('admin-w11-fri-gym', 'cmdhtwtil00000vg18swahirhu', 11, 'Friday', 'GYM', 'pull', NULL, NULL, '04:30', false, NULL, 'Pull Day: Back, Biceps - Reduced Volume', NULL, '{"min": 5, "max": 7, "description": "Light to moderate intensity"}', 'Taper phase volume reduction', NOW()),
('admin-w11-sat-gym', 'cmdhtwtil00000vg18swahirhu', 11, 'Saturday', 'GYM', 'legs', NULL, NULL, '06:00', false, NULL, 'Legs Day: Quads, Hamstrings, Glutes, Calves - Reduced Volume', NULL, '{"min": 5, "max": 7, "description": "Light to moderate intensity"}', 'Taper phase volume reduction', NOW()),
('admin-w11-sat-run', 'cmdhtwtil00000vg18swahirhu', 11, 'Saturday', 'RUNNING', 'long', 12.0, '6:32', '09:00', true, '15 min easy jog + dynamic stretching', '12km steady long run with MadeRunning', '10 min walk + full stretching routine', '{"min": 4, "max": 6, "description": "Comfortable long run"}', 'Taper phase long run', NOW()),
('admin-w11-sun-rest', 'cmdhtwtil00000vg18swahirhu', 11, 'Sunday', 'REST', 'easy', NULL, NULL, NULL, false, NULL, 'Rest Day - Recovery & Stretching', NULL, '{"min": 1, "max": 2, "description": "Complete rest"}', 'Recovery day for adaptation', NOW()),

-- ==================== WEEK 12 (Race Week - Final Taper) ====================
('admin-w12-mon-gym', 'cmdhtwtil00000vg18swahirhu', 12, 'Monday', 'GYM', 'push', NULL, NULL, '04:30', false, NULL, 'Light Push Day: Maintenance Only - Minimal Volume', NULL, '{"min": 3, "max": 5, "description": "Very light maintenance"}', 'Race week minimal stress', NOW()),
('admin-w12-mon-run', 'cmdhtwtil00000vg18swahirhu', 12, 'Monday', 'RUNNING', 'easy', 3.0, '6:32', '17:00', true, '10 min easy jog + dynamic stretching', '3km very easy with MadeRunning', '5 min walk + stretching', '{"min": 1, "max": 3, "description": "Recovery jog"}', 'Race week easy recovery', NOW()),
('admin-w12-tue-gym', 'cmdhtwtil00000vg18swahirhu', 12, 'Tuesday', 'GYM', 'pull', NULL, NULL, '04:30', false, NULL, 'Light Pull Day: Maintenance Only - Minimal Volume', NULL, '{"min": 3, "max": 5, "description": "Very light maintenance"}', 'Race week minimal stress', NOW()),
('admin-w12-wed-run', 'cmdhtwtil00000vg18swahirhu', 12, 'Wednesday', 'RUNNING', 'tempo', 4.0, '5:13', '05:00', true, '10 min easy + 4x100m strides', '2km with some tempo pace with MadeRunning', '10 min easy jog + stretching', '{"min": 4, "max": 6, "description": "Light tempo sharpener"}', 'Race week shakeout', NOW()),
('admin-w12-wed-gym', 'cmdhtwtil00000vg18swahirhu', 12, 'Wednesday', 'GYM', 'legs', NULL, NULL, '06:00', false, NULL, 'Light Legs Day: Activation Only - Minimal Volume', NULL, '{"min": 3, "max": 5, "description": "Very light activation"}', 'Race week minimal stress', NOW()),
('admin-w12-thu-run', 'cmdhtwtil00000vg18swahirhu', 12, 'Thursday', 'RUNNING', 'easy', 3.0, '6:32', '18:00', false, '10 min easy jog + dynamic stretching', '3km very easy (solo)', '5 min walk + stretching', '{"min": 1, "max": 3, "description": "Recovery jog"}', 'Race week easy recovery', NOW()),
('admin-w12-fri-rest', 'cmdhtwtil00000vg18swahirhu', 12, 'Friday', 'REST', 'easy', NULL, NULL, NULL, false, NULL, 'Complete Rest - Pre-Race Recovery', NULL, '{"min": 1, "max": 1, "description": "Complete rest"}', 'Race week complete rest', NOW()),
('admin-w12-sat-run', 'cmdhtwtil00000vg18swahirhu', 12, 'Saturday', 'RUNNING', 'easy', 2.0, '6:32', '09:00', false, '5 min easy jog + dynamic stretching', '2km easy shakeout with strides', '5 min walk + stretching', '{"min": 1, "max": 3, "description": "Pre-race activation"}', 'Race week activation run', NOW()),
('admin-w12-sun-race', 'cmdhtwtil00000vg18swahirhu', 12, 'Sunday', 'RUNNING', 'race', 21.1, '5:41', '09:00', false, '15 min easy jog + dynamic stretching + strides', 'HALF MARATHON RACE - 21.1km at goal pace! Execute the plan!', '15 min cool-down walk + celebration!', '{"min": 8, "max": 10, "description": "RACE EFFORT - Give everything!"}', 'RACE DAY - Execute the plan!', NOW());

-- ✅ VERIFICATION QUERIES
-- Expected: 12 weeks × ~9 sessions per week = 108 sessions total
-- SELECT COUNT(*) FROM generated_sessions WHERE "userId" = 'cmdhtwtil00000vg18swahirhu';

-- Count sessions by week to verify distribution
-- SELECT week, COUNT(*) as session_count FROM generated_sessions WHERE "userId" = 'cmdhtwtil00000vg18swahirhu' GROUP BY week ORDER BY week;

-- Count sessions by type
-- SELECT "sessionType", COUNT(*) as session_count FROM generated_sessions WHERE "userId" = 'cmdhtwtil00000vg18swahirhu' GROUP BY "sessionType";

